[fuzz_lines]
face_num = 1000
sky_num = 1000
horizon_num = 500

[view]
height = 0.5
radius = 0.6
viewport_shape = "Cylinder"
focal = 1.0
spin_speed = 0.02

[scene]
grid = false
sky = false
horizon = false
stars = true
level = "Level1"

[editor]
enabled = false
