[fuzz_lines]
face_num = 500
sky_num = 1000
horizon_num = 500

[view_config]
height = 0.5
radius = 1.0
viewport_shape = "Cylinder"
focal = 1.0
spin_speed = 0.1

[scene_config]
grid = false
sky = false
horizon = false
stars = false