[fuzz_lines]
face_num = 50
sky_num = 1000
horizon_num = 500

[view]
height = 0.5
radius = 0.6
viewport_shape = "Cylinder"
focal = 1.0
spin_speed = 0.02

[scene]
grid = false
sky = false
horizon = false
stars = true
level = "Test1" # Supported: Level1, Empty, Test1, Test2

[editor]
enabled = true
