[fuzz_lines]
face_num = 100
sky_num = 1000
horizon_num = 500

[view]
height = 0.5
radius = 0.6
viewport_shape = "Cylinder"
focal = 1.0
spin_speed = 0.02

[scene]
grid = false
sky = false
horizon = false
stars = true
level = "Load" # Supported: Level1, Empty, Test1, Test2, Test3, Load

[scene.load]
path = "./test_save_level.ron"

[editor]
enabled = true
