[fuzz_lines]
face_num = 200
sky_num = 1000
horizon_num = 500

[view]
height = 0.5
radius = 0.6
viewport_shape = "Cylinder"
focal = 1.0
spin_speed = 0.02

[scene]
grid = true
sky = true
horizon = true
stars = true
level = "Test3" # Supported: Level1, Empty, Test1, Test2, Test3

[editor]
enabled = true
