gui = "Editor"

[draw]
face_scale = 0.8

[draw.fuzz_lines]
face_num = 200
sky_num = 200
horizon_num = 1000

[view]
height = 0.5
radius = 0.6
viewport_shape = "Cylinder"
focal = 0.5
spin_speed = 0.02

[scene]
grid = false
sky = true
horizon = true
stars = true
level = "Empty" # Supported: Level1, Empty, Test1, Test2, Test3, Load

[scene.load]
path = "./test2.ron"

[editor]
enabled = true

[physics]
gravity_acceleration = 2.0